//ANAGRAM CHECK
//GIVEN TWO STRINGS, CHECK WHETHER THEY ARE ANAGRAMS.
//TWO STRINGS ARE CALLED ANAGRAMS IF BOTH OF THEM CONTAIN SAME CHARACTERS WITH SAME FREQUENCIES.

//EXAMPLE:ANAGRAMS FOR "CAR" ARE ARC, ACR, CRA, RAC, RCA

//NOTE: IGNORE CASE-SENSITIVENESS FOR THIS PROBLEM

//INPUT
//->RACE
//->CARE

//OUTPUT
//->TRUE

